// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CacheInfo = { total_size: number, package_count: number, packages: Array<CachePackage>, path: string, };

export type CachePackage = { name: string, version: string, filename: string, size: number, };

export type CachedVersion = { name: string, version: string, filename: string, size: number, installed_version: string | null, is_older: boolean, };

export type ConflictInfo = { package1: string, package2: string, };

export type DependencyEdge = { source: string, target: string, edge_type: string, };

export type DependencyNode = { id: string, name: string, version: string, depth: number, installed: boolean, reason: string | null, repository: string | null, };

export type DependencyTreeResponse = { nodes: Array<DependencyNode>, edges: Array<DependencyEdge>, root: string, max_depth_reached: boolean, warnings: Array<string>, };

export type DismissalState = { signature: string | null, };

export type DowngradeResponse = { packages: Array<CachedVersion>, total: number, };

export type GroupedLogResponse = { groups: Array<LogGroup>, total_groups: number, total_upgraded: number, total_installed: number, total_removed: number, total_other: number, };

export type IgnoreOperationResponse = { success: boolean, package: string, message: string, };

export type IgnoredPackagesResponse = { packages: Array<string>, total: number, };

export type KeyringKey = { fingerprint: string, uid: string, created: string | null, expires: string | null, trust: string, };

export type KeyringStatusResponse = { keys: Array<KeyringKey>, total: number, master_key_initialized: boolean, warnings: Array<string>, };

export type ListReposResponse = { repos: Array<RepoEntry>, };

export type LockRemoveResult = { removed: boolean, error?: string, };

export type LockStatus = { locked: boolean, stale: boolean, lock_path: string, blocking_process?: string, };

export type LogEntry = { timestamp: string, action: string, package: string, old_version: string | null, new_version: string | null, };

export type LogGroup = { id: string, start_time: string, end_time: string, entries: Array<LogEntry>, upgraded_count: number, installed_count: number, removed_count: number, downgraded_count: number, reinstalled_count: number, };

export type LogResponse = { entries: Array<LogEntry>, total: number, total_upgraded: number, total_installed: number, total_removed: number, total_other: number, };

export type MirrorBackup = { timestamp: number, date: string, enabled_count: number, total_count: number, size: number, };

export type MirrorBackupListResponse = { backups: Array<MirrorBackup>, };

export type MirrorEntry = { url: string, enabled: boolean, comment: string | null, };

export type MirrorListResponse = { mirrors: Array<MirrorEntry>, total: number, enabled_count: number, path: string, last_modified: number | null, };

export type MirrorStatus = { url: string, country: string | null, country_code: string | null, last_sync: string | null, delay: number | null, score: number | null, completion_pct: number | null, active: boolean, ipv4: boolean, ipv6: boolean, };

export type MirrorStatusResponse = { mirrors: Array<MirrorStatus>, total: number, last_check: string | null, };

export type MirrorTestResult = { url: string, success: boolean, speed_bps: number | null, latency_ms: number | null, error: string | null, };

export type NewsItem = { title: string, link: string, published: string, summary: string, };

export type NewsReadState = { dismissed: Array<string>, };

export type NewsResponse = { items: Array<NewsItem>, 
/**
 * True when served from the on-disk cache because the live fetch failed.
 */
stale?: boolean, };

export type OrphanPackage = { name: string, version: string, description: string | null, installed_size: number, install_date: number | null, repository: string | null, };

export type OrphanResponse = { orphans: Array<OrphanPackage>, total_size: number, };

export type Package = { name: string, version: string, description: string | null, installed_size: number, install_date: number | null, reason: string, repository: string | null, };

export type PackageDetails = { name: string, version: string, description: string | null, url: string | null, licenses: Array<string>, groups: Array<string>, provides: Array<string>, depends: Array<string>, optdepends: Array<string>, conflicts: Array<string>, replaces: Array<string>, required_by: Array<string>, optional_for: Array<string>, installed_size: number, packager: string | null, architecture: string | null, build_date: number, install_date: number | null, reason: string, validation: Array<string>, repository: string | null, update_stats: UpdateStats | null, };

export type PackageListResponse = { packages: Array<Package>, total: number, total_explicit: number, total_dependency: number, repositories: Array<string>, warnings: Array<string>, };

export type PackageSecurityAdvisory = { package: string, severity: string, advisory_type: string, avg_name: string, cve_ids: Array<string>, fixed_version: string | null, status: string, };

export type PacnewFile = { path: string, package: string, kind: string, };

export type PacnewStatus = { has_pacnew: boolean, files: Array<PacnewFile>, };

export type PreflightKeyInfo = { fingerprint: string, uid: string, };

export type PreflightResponse = { success: boolean, error?: string, conflicts?: Array<ConflictInfo>, replacements?: Array<ReplacementInfo>, removals?: Array<string>, providers?: Array<ProviderChoice>, import_keys?: Array<PreflightKeyInfo>, warnings?: Array<PreflightWarning>, packages_to_upgrade: number, total_download_size: number, };

export type PreflightWarning = { id: string, severity: WarningSeverity, title: string, message: string, packages: Array<string>, };

export type ProviderChoice = { dependency: string, providers: Array<string>, };

export type RebootStatus = { requires_reboot: boolean, reason: string, running_kernel: string | null, installed_kernel: string | null, kernel_package: string | null, updated_packages: Array<string>, };

export type RefreshMirrorsResponse = { mirrors: Array<MirrorEntry>, total: number, last_check: string | null, };

export type ReplacementInfo = { old_package: string, new_package: string, };

export type RepoBackup = { timestamp: number, date: string, repo_count: number, enabled_count: number, size: number, };

export type RepoBackupListResponse = { backups: Array<RepoBackup>, };

export type RepoDirectiveFull = { directive_type: string, value: string, enabled: boolean, };

export type RepoEntry = { name: string, enabled: boolean, sig_level: string | null, directives: Array<RepoDirectiveFull>, };

export type RestartBlocked = "session_critical" | "cockpit_session" | "cockpit_transport";

export type RestoreMirrorBackupResponse = { success: boolean, backup_path: string | null, message: string, };

export type RestoreRepoBackupResponse = { success: boolean, backup_path: string | null, message: string, };

export type SaveMirrorlistResponse = { success: boolean, backup_path: string | null, message: string, };

export type SaveReposResponse = { success: boolean, backup_path: string | null, message: string, };

export type ScheduleConfig = { enabled: boolean, mode: string, schedule: string, max_packages: number, timer_active: boolean, timer_next_run: string | null, };

export type ScheduleMode = "check" | "upgrade";

export type ScheduleSetResponse = { success: boolean, message: string, };

export type ScheduledRunEntry = { timestamp: string, mode: string, success: boolean, status: string, packages_checked: number, packages_upgraded: number, error: string | null, details: Array<string>, };

export type ScheduledRunsResponse = { runs: Array<ScheduledRunEntry>, total: number, };

export type SearchResponse = { results: Array<SearchResult>, total: number, total_installed: number, total_not_installed: number, repositories: Array<string>, };

export type SearchResult = { name: string, version: string, description: string | null, repository: string, installed: boolean, installed_version: string | null, };

export type SecurityInfoAdvisory = { name: string, date: string, severity: string, advisory_type: string, };

export type SecurityInfoGroup = { name: string, status: string, severity: string, };

export type SecurityInfoIssue = { name: string, severity: string, issue_type: string, status: string, };

export type SecurityInfoResponse = { name: string, advisories: Array<SecurityInfoAdvisory>, groups: Array<SecurityInfoGroup>, issues: Array<SecurityInfoIssue>, };

export type SecurityResponse = { advisories: Array<PackageSecurityAdvisory>, 
/**
 * True when served from the on-disk cache because the live fetch failed.
 */
stale?: boolean, };

export type ServiceRestart = { name: string, pid: number, affected_packages: Array<string>, reason: string, restart_blocked?: RestartBlocked | null, };

export type ServicesStatus = { restart_required: boolean, services: Array<ServiceRestart>, };

/**
 * Wire mirror of archweb_client's Signoff so the type can derive TS bindings
 * without depending on the external crate's type. Mapped from the client type
 * in the signoff handler.
 */
export type Signoff = { user: string, created: string, revoked: boolean, };

export type SignoffActionResponse = { success: boolean, pkgbase: string, action: string, error: string | null, };

export type SignoffGroupWithLocal = { pkgbase: string, pkgnames: Array<string>, version: string, arch: string, repo: string, packager: string, comments?: string, last_update: string, known_bad: boolean, approved: boolean, required: number, enabled: boolean, signoffs: Array<Signoff>, local_version: string | null, version_match: VersionMatch, };

export type SignoffListResponse = { signoff_groups: Array<SignoffGroupWithLocal>, total: number, };

export type StreamEvent = { "type": "log", level: string, message: string, } | { "type": "progress", operation: string, package: string, percent: number, current: number, total: number, } | { "type": "download", filename: string, event: string, downloaded?: number, total?: number, } | { "type": "event", event: string, package?: string, } | { "type": "complete", success: boolean, message?: string, } | { "type": "mirror_test", url: string, current: number, total: number, result: MirrorTestResult, };

export type SyncPackageDetails = { name: string, version: string, description: string | null, url: string | null, licenses: Array<string>, groups: Array<string>, provides: Array<string>, depends: Array<string>, optdepends: Array<string>, conflicts: Array<string>, replaces: Array<string>, download_size: number, installed_size: number, packager: string | null, architecture: string | null, build_date: number, repository: string, };

export type UpdateInfo = { name: string, current_version: string, new_version: string, download_size: number, current_size: number, new_size: number, repository: string, ignored: boolean, };

export type UpdateStats = { update_count: number, first_installed: string | null, last_updated: string | null, avg_days_between_updates: number | null, };

export type UpdatesResponse = { updates: Array<UpdateInfo>, warnings: Array<string>, };

export type VersionMatch = "match" | "mismatch" | "not_installed";

export type WarningSeverity = "info" | "warning" | "danger";
